"""Первая миграция

Revision ID: 4a8c96a3ac0e
Revises: 
Create Date: 2025-05-02 15:47:32.089863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a8c96a3ac0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('CLIENT', 'SELLER', 'VETERINARIAN', 'ADMIN', 'OWNER', name='role'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('CLIENT', 'SELLER', 'VETERINARIAN', 'ADMIN', 'OWNER', name='role'),
               nullable=False)

    # ### end Alembic commands ###
