"""empty message

Revision ID: 75a218946aba
Revises: 4a8c96a3ac0e
Create Date: 2025-05-06 14:20:14.473311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a218946aba'
down_revision = '4a8c96a3ac0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('chat_message_receiver_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chat_message_sender_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('sender_id')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('is_from_ai')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_from_ai', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_message_sender_id_fkey', 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key('chat_message_receiver_id_fkey', 'user', ['receiver_id'], ['id'])
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_path')
        batch_op.drop_column('reply')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
